---
name: Build Screenly Chrome Extension

on:
  pull_request:
    branches:
    - master
    - production
  push:
    branches:
      - master
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Build and Generate Artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker images
        run: |
          docker compose build

      - name: Run Unit Tests
        run: |
          docker run \
            --rm \
            -v $(pwd):/app:delegated \
            -v /app/node_modules \
            sce_webpack:latest \
            /bin/bash -c "npx webpack --config webpack.dev.js && npm run test"

      - name: Build and Package the Extension
        run: |
          mkdir artifacts
          docker run \
            --rm \
            -v $(pwd)/artifacts:/app/artifacts:delegated \
            -v /app/artifacts/node_modules \
            sce_webpack:latest \
            /bin/bash -c "npm run build && cp -r dist/ artifacts/"

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenly-chrome-extension
          path: artifacts/dist
